<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Ctrlp.PrintAgent.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ctrlp.PrintAgent.Contracts\Ctrlp.PrintAgent.Contracts.csproj" />
  </ItemGroup>
</Project>
